name: Build app in NCS docker container

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-24.04
    container: ghcr.io/nrfconnect/sdk-nrf-toolchain:v3.1.1
    defaults:
      run:
        # Bash shell is needed to set toolchain related environment variables in docker container
        # It is a workaround for GitHub Actions limitation https://github.com/actions/runner/issues/1964
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: application

      - name: Prepare west project
        run: |
          west init -l application
          west update -o=--depth=1 -n

      - name: Build firmware
        working-directory: application
        run: |
          west build -b promicro app

      - name: Store binary files
        uses: actions/upload-artifact@v4
        with:
          name: binary
          path: |
            application/build/app/zephyr/zephyr.signed.bin